# Generated by Django 3.2.13 on 2022-06-26 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PROCESSING', max_length=64)),
                ('tickets', models.ManyToManyField(related_name='reservations', to='ticket.Ticket')),
            ],
        ),
    ]
