# Generated by Django 3.2.13 on 2022-06-26 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('event_type', models.CharField(choices=[('THEATRE', 'Theatre'), ('CONCERT', 'Concert'), ('CLUB', 'Club'), ('STANDUP', 'Standup')], default='THEATRE', max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
